name: Update Gradle Wrapper to 7.6

on:
  push:
    branches:
      - main  # Adjust to your branch if necessary

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest  # You can change this to windows-latest or macos-latest if needed

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up JDK 17 using Adoptium
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptium'  # Corrected distribution name

      # Update Gradle wrapper to version 7.6
      - name: Update Gradle wrapper to version 7.6
        run: ./gradlew wrapper --gradle-version=7.6

      # Commit and push changes to GitHub
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add gradle/wrapper/gradle-wrapper.properties gradle/wrapper/gradle-wrapper.jar
          git commit -m "Update Gradle wrapper to version 7.6"
          git push
