name: Update Gradle Wrapper to 7.6

on:
  push:
    branches:
      - main  # You can change this to your branch if you use a different one

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest  # You can change this to windows-latest or macos-latest if needed

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'  # or use 'zulu' if you prefer

      # Run the gradle wrapper command to update to version 7.6
      - name: Update Gradle wrapper to version 7.6
        run: ./gradlew wrapper --gradle-version=7.6

      # Commit and push the changes
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add gradle/wrapper/gradle-wrapper.properties gradle/wrapper/gradle-wrapper.jar
          git commit -m "Update Gradle wrapper to version 7.6"
          git push
